%! abjad.LilyPondFile._get_format_pieces()
\version "2.22.1"
%! abjad.LilyPondFile._get_format_pieces()
\language "english"
%! abjad.LilyPondFile._get_formatted_includes()
\include "ilys/variables.ily"
%! abjad.LilyPondFile._get_formatted_includes()
\include "ilys/common_layout.ily"

\context Score = "Score"
<<
    \context StaffGroup = "Percussion"
    <<
        \context Staff = "cym_cow"
        \with
        {
            \override StaffSymbol.line-count = 3
            \override StaffSymbol.line-positions = #'(-4 0 4)
            instrumentName = \markup{\fontsize #-1 { \sans \column{ "large cymbal" "small cymbal" "cowbell" }}}
        }
        <<
            \context Voice = "largecymb"
            \with
            {
                \override NoteHead.style = #'cross
                \override Stem.direction = #up
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    \clef "percussion"
                    r8
                    r16
                    r32
                    g'32
                    ~
                }
                {
                    g'32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r16
                    g'16
                    r8
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    g'16
                    ~
                }
                {
                    g'32
                    r32
                    g'32
                    r32
                    r8
                }
                {
                    r8
                    r16
                    r32
                    g'32
                }
                {
                    r8
                    r16
                    g'32
                    r32
                }
                {
                    r4
                }
                {
                    g'32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    g'32
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    g'32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    g'16.
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    g'32
                    r32
                    r16
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
            \context Voice = "smallcymb"
            \with
            {
                \override NoteHead.style = #'cross
                \override Stem.direction = #up
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    r8
                    c'16.
                    r32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    c'32
                    - \markup{\bold " ,"}
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    c'32
                    - \markup{\bold " ,"}
                    r32
                    c'32
                    - \markup{\bold " ,"}
                    ~
                }
                {
                    c'32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    c'32
                    - \markup{\bold " ,"}
                    r32
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    c'32
                    - \markup{\bold " ,"}
                    r32
                    r16
                }
                {
                    r4
                }
            }
            \context Voice = "cow"
            \with
            {
                \override Stem.direction = #down
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    r8
                    f32
                    r32
                    r16
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    f16
                    r32
                    r32
                    f32
                    ~
                }
                {
                    f32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    f16
                    r32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    f16.
                    f16.
                    ~
                }
                {
                    f16
                    r32
                    f32
                    r8
                }
                {
                    r32
                    f16
                    r32
                    f16
                    r16
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
        >>
        \context Staff = "conga_bongo"
        \with
        {
            \override StaffSymbol.line-count = 2
            \override StaffSymbol.line-positions = #'(-4 4)
            instrumentName = \markup{\fontsize #-1 {\sans \column{ "bongo" "conga" }}}
        }
        <<
            \context Voice = "bongo"
            \with
            {
                \override Stem.direction = #up
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    \clef "percussion"
                    r4
                }
                {
                    r16
                    g'16
                    - \markup{\sans "mf."}
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r32
                    g'32
                    - \markup{\sans "sl."}
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    g'32
                    - \markup{\sans "sl."}
                    r32
                }
                {
                    r8
                    g'32
                    - \markup{\sans "mf."}
                    r32
                    r16
                }
                {
                    r8
                    g'32
                    - \markup{\sans "sl."}
                    r32
                    r16
                }
                {
                    r8
                    r32
                    g'32
                    - \markup{\sans "sl."}
                    r16
                }
                {
                    r4
                }
                {
                    r32
                    g'16
                    - \markup{\sans "mf."}
                    r32
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    \times 2/3
                    {
                        r8
                        g'8
                        - \markup{\sans "sl."}
                        r8
                    }
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    g'16
                    - \markup{\sans "mf."}
                    r32
                    r16
                }
                {
                    r8
                    r16
                    g'32
                    - \markup{\sans "mf."}
                    r32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    \times 2/3
                    {
                        r8
                        r8
                        g'8
                        - \markup{\sans "mf."}
                        ~
                    }
                }
                {
                    \times 2/3
                    {
                        g'8
                        r8
                        r8
                    }
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    g'32
                    - \markup{\sans "mf."}
                    r32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r32
                    g'16.
                    - \markup{\sans "sl."}
                    r8
                }
            }
            \context Voice = "conga"
            \with
            {
                \override Stem.direction = #down
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    f16
                    - \markup{\sans "sl."}
                    r32
                }
                {
                    r4
                }
                {
                    r8
                    f32
                    - \markup{\sans "sl."}
                    r32
                    r16
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    f32
                    - \markup{\sans "sl."}
                    r32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    f32
                    - \markup{\sans "mf."}
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    f32
                    - \markup{\sans "mf."}
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
        >>
        \context Staff = "tom_snare"
        \with
        {
            \override StaffSymbol.line-count = 2
            \override StaffSymbol.line-positions = #'(-4 4)
            instrumentName = \markup{\fontsize #-1 {\sans \column{ "snare drum" "large tom" }}}
        }
        <<
            \context Voice = "snare"
            \with
            {
                \override Stem.direction = #up
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    \clef "percussion"
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r8
                }
                {
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    g'16
                    - \markup{+}
                    r16
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                }
                {
                    r32
                    g'32
                    - \markup{+}
                    r16
                    r8
                }
                {
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    g'32
                    - \markup{+}
                    r32
                    r16
                }
                {
                    g'32
                    - \markup{+}
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                    r16
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                }
                {
                    r4
                }
                {
                    r16
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                }
                {
                    r8
                    r16
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                }
                {
                    r4
                }
                {
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                    r16
                    r8
                }
                {
                    r8
                    r16
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                }
                {
                    r16
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                    r8
                }
                {
                    r4
                }
                {
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r16
                    r16
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                    r32
                }
                {
                    r8
                    r16
                    r32
                    g'32
                    - \markup{\fontsize #-2 \musicglyph #"scripts.flageolet"}
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
            \context Voice = "tom"
            \with
            {
                \override Stem.direction = #down
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    r4
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    f32
                    r32
                }
                {
                    f32
                    r32
                    r16
                    r16
                    f32
                    r32
                }
                {
                    r16
                    r32
                    f32
                    r32
                    f32
                    r32
                    f32
                }
                {
                    f32
                    r32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r16
                    f32
                    r32
                    f32
                    r32
                    r16
                }
                {
                    r4
                }
                {
                    r16
                    r32
                    f32
                    r16
                    r32
                    f32
                }
                {
                    r16
                    f32
                    r32
                    f32
                    r32
                    r32
                    f32
                }
                {
                    r4
                }
                {
                    r8
                    r32
                    f16
                    r32
                }
                {
                    r8
                    r32
                    f32
                    r16
                }
                {
                    f32
                    f32
                    r16
                    r8
                }
                {
                    r4
                }
                {
                    r8
                    r16
                    r32
                    f32
                }
                {
                    r4
                }
                {
                    r32
                    f32
                    r16
                    f32
                    r32
                    r32
                    f32
                }
                {
                    r8
                    r16
                    r32
                    f32
                    ~
                }
                {
                    f32
                    r32
                    f32
                    f32
                    r32
                    f32
                    r16
                }
                {
                    f32
                    f32
                    r16
                    r16
                    r32
                    f32
                }
                {
                    r4
                }
                {
                    \times 2/3
                    {
                        f8
                        f4
                        ~
                    }
                }
                {
                    f8
                    ~
                    f32
                    r32
                    r16
                }
                {
                    r16
                    f16
                    r8
                }
                {
                    r4
                }
                {
                    r32
                    f32
                    r16
                    r8
                }
                {
                    r16
                    r32
                    f32
                    r16
                    r32
                    f32
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
        >>
        \context Staff = "shaker_cabassa"
        \with
        {
            \override StaffSymbol.line-count = 2
            \override StaffSymbol.line-positions = #'(-4 4)
            instrumentName = \markup{\fontsize #-1 {\sans \column{ "cabassa" "metal shaker" }}}
        }
        <<
            \context Voice = "cabassaV"
            \with
            {
                \override NoteHead.style = #'xcircle
                \override Stem.direction = #up
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    \clef "percussion"
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r32
                    g'16
                    r32
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r4
                }
            }
            \context Voice = "shaker"
            \with
            {
                \override NoteHead.style = #'xcircle
                \override Stem.direction = #down
            }
            {
                {
                    \tempo 4=60
                    \time 1/4
                    r8
                    r16
                    r32
                    f32
                }
                {
                    r16
                    f32
                    r32
                    r8
                }
                {
                    r16
                    r32
                    f32
                    r32
                    f32
                    r16
                }
                {
                    f32
                    r32
                    f32
                    r32
                    r16
                    f32
                    r32
                }
                {
                    f32
                    f32
                    r16
                    f32
                    f32
                    r32
                    f32
                }
                {
                    r8
                    r16
                    f32
                    r32
                }
                {
                    r16
                    f32
                    r32
                    r8
                }
                {
                    r16
                    f32
                    r32
                    f32
                    f32
                    f32
                    f32
                }
                {
                    f32
                    f16.
                    f32
                    r32
                    f32
                    r32
                }
                {
                    r16
                    r32
                    f32
                    f32
                    r32
                    f32
                    f32
                }
                {
                    f32
                    r32
                    f32
                    r32
                    f32
                    f32
                    r32
                    f32
                }
                {
                    r32
                    f32
                    r16
                    r8
                }
                {
                    r32
                    f32
                    r32
                    f32
                    r8
                }
                {
                    r32
                    f32
                    f32
                    r32
                    r32
                    f32
                    r16
                }
                {
                    r8
                    f32
                    r32
                    r16
                }
                {
                    f32
                    r32
                    r32
                    f32
                    r8
                }
                {
                    r8
                    r16
                    r32
                    f32
                }
                {
                    f32
                    r32
                    r32
                    f32
                    r8
                }
                {
                    r16
                    r32
                    f32
                    f32
                    r32
                    f32
                    f32
                }
                {
                    r16
                    f32
                    f8
                    f32
                }
                {
                    f32
                    r32
                    r16
                    r8
                }
                {
                    f32
                    f32
                    r16
                    r32
                    f32
                    r16
                }
                {
                    r4
                }
                {
                    r16
                    f32
                    r32
                    r8
                }
                {
                    r4
                }
                {
                    r4
                }
                {
                    r16
                    f32
                    r32
                    r32
                    f32
                    r16
                }
                {
                    r16
                    r32
                    f32
                    f32
                    r32
                    r16
                }
                {
                    f32
                    f32
                    r32
                    f32
                    f32
                    r32
                    r16
                }
                {
                    r4
                }
                {
                    r8
                    f32
                    r32
                    r16
                }
                {
                    r32
                    f32
                    r16
                    r8
                }
            }
        >>
    >>
>>